//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     稳定好用的Orm【Chloe:http://www.52chloe.com/】
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using PetaPoco;
namespace FrameWork.Entity.Entity
{
    /// <summary>
    /// 实体类Log4net。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableName("Log4net")]
    [PrimaryKey("Id",true)]
    public partial class Log4net
    {
        #region Model
        /// <summary>
        /// 主键
        /// </summary>	
        public int Id { get; set; }

		/// <summary>
		/// 日志级别
		/// </summary>	
		public string Level { get; set; }

		/// <summary>
		/// 记录所属项目
		/// </summary>	
		public string Logger { get; set; }

		/// <summary>
		/// ip地址
		/// </summary>	
		public string Host { get; set; }

		/// <summary>
		/// 记录日期
		/// </summary>	
		public DateTime? Date { get; set; }

		/// <summary>
		/// 线程id
		/// </summary>	
		public string Thread { get; set; }

		/// <summary>
		/// 异常消息
		/// </summary>	
		public string Message { get; set; }

		/// <summary>
		/// 异常
		/// </summary>	
		public string Exception { get; set; }

		/// <summary>
		/// 是否处理
		/// </summary>	
		public bool? IsProgress { get; set; }

		/// <summary>
		/// 备注
		/// </summary>	
		public string Note { get; set; }

		#endregion
}
}