//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://ITdos.com/Dos/ORM/Index.html
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using PetaPoco;

namespace FrameWork.Entity.Entity
{
    /// <summary>
    /// 实体类T_JobBanner。(属性说明自动提取数据库字段的描述信息)
    /// </summary>
    [TableName("T_JobBanner")]
    [PrimaryKey("Id")]
    public partial class T_JobBanner
    {
        #region Model
        /// <summary>
        /// 
        /// </summary>	
        public int Id { get; set; }

        /// <summary>
        /// 
        /// </summary>	
        public string PicUrl { get; set; }

        /// <summary>
        /// 
        /// </summary>	
        public string OpenUrl { get; set; }

        /// <summary>
        /// 是否启用
        /// </summary>	
        public bool IsUsed { get; set; }

        /// <summary>
        /// 是否删除
        /// </summary>	
        public bool IsDel { get; set; }

        /// <summary>
        /// 编辑人id
        /// </summary>	
        public int ModifyUserId { get; set; }

        /// <summary>
        /// 编辑时间
        /// </summary>	
        public DateTime ModifyTime { get; set; }

        /// <summary>
        /// 创建人id
        /// </summary>	
        public int CreateUserId { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>	
        public DateTime CreateTime { get; set; }

        #endregion
    }
}