//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     稳定好用的Orm【Chloe:http://www.52chloe.com/】
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using PetaPoco;
namespace FrameWork.Entity.Entity
{
    /// <summary>
    /// 新闻资讯表
    /// </summary>
    [TableName("T_News")]
    [PrimaryKey("Id", true)]
    public class T_News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string Image { get; set; }
        public string Summary { get; set; }
        public int ViewCount { get; set; }
        public int UpvoteCount { get; set; }
        public int CollectCount { get; set; }
        public int ShareCount { get; set; }
        public bool IsUsed { get; set; }
        public bool IsDel { get; set; }
        public int ModifyUserId { get; set; }
        public DateTime ModifyTime { get; set; }
        public int CreateUserId { get; set; }
        public DateTime CreateTime { get; set; }
    }
}